#!/bin/bash

DIR=/home/student334/Desktop/CS334
IP_ADDRESS=$(hostname -I)


echo $IP_ADDRESS > ${DIR}/rasberrypi/ip.md

cd ${DIR}/rasberrypi
git pull
git add ${DIR}/rasberrypi
 /boot/firmware/config.txt
git commit -m "updated IP"
git push

